### ISSUE TITLE
CopraRNA.pl: no postscript 'convert' 

### ISSUE THREAD

**Issue by martin-raden** [JensGeorg/CopraRNA#11]
1) extend `script_R_plots_8.R` such that the PNG files are directly produced:

- no PS output
- create PNG output
- create small PNG output

2) update CopraRNA.pl

- no PNG creation via convert
- only PNG shrinkage via convert from PNG sources

**Comment by JensGeorg** [comment]
I extendend the script to produce directly usable full size pngs. However, proper resizing to thumbnails would require another package.
