### ISSUE TITLE
conservation_heatmap PNG missing

### ISSUE THREAD

**Issue by martin-raden** [JensGeorg/CopraRNA#15]
moin @JensGeorg ,
die alte version hat wohl noch folgende files angelegt:
- conservation_heatmap.png
- conservation_heatmap_small.png
ist das verloren gegangen oder nicht mehr benötigt?

**Comment by JensGeorg** [comment]
Da gibt es nur noch das PDF. Ich kann aber noch ein PNG für den Webserver
erstellen.

Martin Raden <notifications@github.com> schrieb am Do., 30. Juli 2020,
18:34:

**Comment by martin-raden** [comment]
passt scho, wollt nur sichergehen...
