### ISSUE TITLE
jalview_props.txt nicht im repo...

### ISSUE THREAD

**Issue by martin-raden** [JensGeorg/CopraRNA#17]
Moin @JensGeorg 

kann es sein, dass du die Datei `copra_aux/jalview_props.txt` nicht ins github repo eingecheckt hast? finde sie nirgends, wird aber gebraucht, gerade für die jalview-memory issue #16

**Comment by JensGeorg** [comment]
Das kann sein. Ich habe es jetzt pepushed.
