### ISSUE TITLE
skip anti-sense results from IntaRNA output

### ISSUE THREAD

**Issue by martin-raden** [JensGeorg/CopraRNA#7]
... BEFORE p-values are computed.

that way, p-values are more reliable and no pseudo interactions are listed in results table

**Comment by JensGeorg** [comment]
I added the parameter "--hybrid_threshold". Interactions are removed from the CopraRNA calculations if the hybrid covers >= "hybrid_threshold" of the sRNA. Those homologs are excluded from cluster.tab before p-value combination.
